services:
  - type: web
    name: clixter-server
    env: node
    region: oregon
    plan: free
    repo: https://github.com/anuxoo001/Clixter
    branch: main
    root: server
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URLS
        sync: false
